version: "2"

services: 
  client:
    build: phinestversion-client
    ports:
      - "4200:4200"
    volumes:
      - ./phinestversion-client:/usr/src/app
  api:
    build: phinestversion-api
    ports:
      - "8000:8000"
